import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import {Sora} from "next/font/google";
import backgroundImage from "./assests/background.png"
import { url } from "inspector";



const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sora.className}>
      <head>

      </head>
      <body className="w-full h-[100vh]" style={{backgroundImage: `url(${backgroundImage.src})`, backgroundSize:"cover", backgroundRepeat:"no-repeat", backgroundPosition:"center"}}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
